version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        #TaskDefinition: "arn:aws:ecs:ap-southeast-1:99999999999999:task-definition/NewMathServiceTask:2"
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:652089208055:task-definition/web-ec2-task:1"
        LoadBalancerInfo:
          ContainerName: "web"
          ContainerPort: 80
